version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
  web:
    image: php:7.4-apache
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
volumes:
  db_data:
